name: Deploy Sanity Studio

on:
  push:
    branches: [live]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy       # 👈 this matches the environment you created
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Deploy to Sanity
        run: npx sanity deploy --non-interactive --token "$SANITY_AUTH_TOKEN"
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
